version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
    timezone: Asia/Tokyo
  open-pull-requests-limit: 100
  ignore:
  - dependency-name: electron
    versions:
    - 11.2.2
    - 11.2.3
    - 12.0.0
    - 12.0.1
    - 12.0.2
    - 12.0.4
  - dependency-name: "@types/node"
    versions:
    - 14.14.22
    - 14.14.25
    - 14.14.28
    - 14.14.31
    - 14.14.32
    - 14.14.34
    - 14.14.35
    - 14.14.37
  - dependency-name: "@vue/cli-plugin-babel"
    versions:
    - 4.5.12
  - dependency-name: node-abi
    versions:
    - 2.20.0
    - 2.21.0
  - dependency-name: svg-sprite-loader
    versions:
    - 6.0.0
    - 6.0.2
    - 6.0.5
  - dependency-name: eslint-plugin-vue
    versions:
    - 7.7.0
    - 7.8.0
  - dependency-name: lottie-web
    versions:
    - 5.7.7
  - dependency-name: vue-i18n
    versions:
    - 8.23.0
    - 8.24.1
    - 8.24.2
  - dependency-name: "@vue/cli-plugin-eslint"
    versions:
    - 4.5.12
  - dependency-name: highlight.js
    versions:
    - 10.7.1
  - dependency-name: image-size
    versions:
    - 0.9.5
  - dependency-name: typescript
    versions:
    - 4.1.3
    - 4.1.4
    - 4.1.5
    - 4.2.2
    - 4.2.3
  - dependency-name: "@vue/eslint-config-typescript"
    versions:
    - 7.0.0
  - dependency-name: "@vue/eslint-config-standard"
    versions:
    - 6.0.0
  - dependency-name: sass-loader
    versions:
    - 10.1.1
    - 11.0.0
  - dependency-name: vue-axios
    versions:
    - 3.2.3
    - 3.2.4
